/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GravatarRegistry } from "./GravatarRegistry";
export * as factories from "./factories";
export { GravatarRegistry__factory } from "./factories/GravatarRegistry__factory";
